### ISSUE TITLE
Local phone numbers for US

### ISSUE THREAD

**Issue by pouliusm** [ttacon/libphonenumber#68]
If I have:
num, err := Parse("320-5478", "US")

I should get an error. AM I right? But I get +13205478.
I mean that this number does not include domestic (state) code.

**Comment by ttacon** [comment]
This is expected functionality for US phone numbers as area codes are strictly required (i.e. if you dial a phone with the same area code as the one that you're calling from the call will correctly route). Closing for now. Thanks! If you feel this should function otherwise, I'd welcome a PR for us to discuss on!
